language: perl
perl:
  - "5.10" # Ugh
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
  - "5.30-ld" # -Duselongdouble
  - "dev"
  - "blead"
matrix:
  allow_failures:
    - perl: blead       # ignore failures for blead perl
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto